import './App.css'

function App() {
  return (
    <main className="min-h-screen bg-[#f4f7f8] text-slate-800"><aside className="fixed hidden h-screen w-64 flex-col bg-[#123b4a] p-7 text-white md:flex"><div className="mb-12"><p className="text-xs uppercase tracking-[0.25em] text-cyan-200">RPL / PRODI</p><h1 className="mt-2 text-2xl font-bold">Arsip Digital</h1></div><nav className="space-y-2 text-sm"><a className="block rounded-xl bg-white/15 px-4 py-3 font-semibold" href="#dashboard">Dashboard</a><a className="block rounded-xl px-4 py-3 text-cyan-100 hover:bg-white/10" href="#arsip">Arsip Dokumen</a><a className="block rounded-xl px-4 py-3 text-cyan-100 hover:bg-white/10" href="#upload">Upload Dokumen</a><a className="block rounded-xl px-4 py-3 text-cyan-100 hover:bg-white/10" href="#master">Data Master</a><a className="block rounded-xl px-4 py-3 text-cyan-100 hover:bg-white/10" href="#audit">Audit Log</a></nav><div className="mt-auto rounded-2xl bg-[#0d303d] p-4 text-sm"><p className="text-cyan-100">Penyimpanan</p><p className="mt-2 font-bold">68.4 GB / 250 GB</p><div className="mt-3 h-2 rounded-full bg-white/15"><div className="h-2 w-[27%] rounded-full bg-cyan-300" /></div></div></aside><section className="md:ml-64"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-6 py-5 md:px-10"><div><p className="text-sm text-slate-500">Rabu, 30 September 2026</p><h2 className="text-2xl font-bold text-slate-900">Selamat datang kembali</h2></div><span className="rounded-full bg-[#e0f1f3] px-3 py-2 text-sm font-semibold text-[#123b4a]">Admin RPL</span></header><div className="mx-auto max-w-7xl space-y-8 p-6 md:p-10"><div className="rounded-3xl bg-[#d8eef0] p-7 md:p-10"><p className="text-sm font-semibold uppercase tracking-wider text-[#23707b]">Pusat arsip prodi</p><h3 className="mt-2 max-w-2xl text-3xl font-bold tracking-tight text-[#123b4a] md:text-5xl">Temukan dokumen penting dalam hitungan detik.</h3><div className="mt-7 flex max-w-2xl gap-3"><input className="min-w-0 flex-1 rounded-xl border-0 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-[#23707b]" placeholder="Cari judul, NIM, tag, atau isi dokumen..." /><button className="rounded-xl bg-[#123b4a] px-5 py-3 font-semibold text-white">Cari</button></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Total Dokumen','1,248','+12 bulan ini'],['Upload Bulan Ini','86','19 menunggu indeks'],['Dokumen Draft','24','Perlu dilengkapi'],['Pengguna Aktif','18','100% akun internal']].map(([label, value, note]) => <div className="rounded-2xl border border-slate-200 bg-white p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold text-slate-900">{value}</p><p className="mt-2 text-xs font-medium text-emerald-600">{note}</p></div>)}</div></div></section></main>
  )
}

export default App
